### ISSUE TITLE
pointing to OLD Server

### ISSUE THREAD

**Issue by Conchipedia** [ClayC90/ClaysTKSite_Issues#14]
on site when you click on visit
![snap2587](https://user-images.githubusercontent.com/29383891/44936721-c56b8a80-ad6d-11e8-9071-45c15d17fec8.png)

you get this
![snap2586](https://user-images.githubusercontent.com/29383891/44936731-cd2b2f00-ad6d-11e8-8997-429295b82e2a.png)

**Comment by ClayC90** [comment]
Fixed
